name: quick_bite
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  iconsax: ^0.0.8
  lottie: ^3.1.2
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animation/
    - assets/products/burger/
    - assets/products/salad/
    - assets/products/drink/
    - assets/products/desserts/
    - assets/products/chicken/
    - assets/products/sandwish/
    - assets/icons/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
